# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=144)),
                ('totalAnswers', models.IntegerField()),
                ('yesCount', models.IntegerField()),
                ('noCount', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='currentAnswers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='noCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='yesCount',
            field=models.IntegerField(default=0),
        ),
    ]
