# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 01:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import questionApp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionApp', '0002_auto_20160424_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='answered',
            name='user',
            field=models.ForeignKey(default=questionApp.models.get_user_default_id, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.ForeignKey(default=questionApp.models.get_user_default_id, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
